# Generated by Django 4.0.2 on 2022-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.TextField()),
                ('createed_Date', models.DateTimeField(auto_now_add=True)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('content', models.TextField()),
                ('createed_Date', models.DateTimeField(auto_now_add=True)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_type', models.CharField(choices=[('link', 'link'), ('static', 'static'), ('system', 'system')], max_length=25)),
                ('content_msg', models.CharField(max_length=50)),
                ('createed_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('content', models.TextField()),
                ('createed_Date', models.DateTimeField(auto_now_add=True)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('protein_id', models.AutoField(primary_key=True, serialize=False)),
                ('aas', models.TextField()),
                ('dna', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
