# Generated by Django 4.0.2 on 2022-02-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='createed_Date',
            new_name='created_Date',
        ),
    ]
