# Generated by Django 4.0.2 on 2022-02-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_createed_date_notification_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.document'),
        ),
        migrations.AddField(
            model_name='comment',
            name='protein_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.protein'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='document_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.document'),
        ),
        migrations.AddField(
            model_name='notification',
            name='protein_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.protein'),
        ),
    ]
